### ISSUE TITLE
当青果跑团log日志模块开启时，能否支持将OlivOSOnebotV11转发的消息也记入其中？

### ISSUE THREAD

**Issue by kagangtuya-star** [lunzhiPenxil/OlivOSOnebotV11#2]
我使用了OlivOSOnebotV11将梨骰接入了kook与dodo，并准备使用青果的跑团日志模块记录log，但日志模块并没有办法记录由转发器发回的消息。

**Comment by lunzhiPenxil** [comment]
这可能需要深度支持调整OlivOS的message_sent事件机制并在青果的日志模块做出对应调整，后续将会跟进

**Comment by lunzhiPenxil** [comment]
目前采用了注入方法实现了该功能，请参考https://github.com/OlivOS-Team/OlivaDiceLogger/commit/c0218741c122d982c65038d80a58abf51761f565
并获取对应的action版本https://github.com/OlivOS-Team/OlivaDiceLogger/actions/runs/7096115960/job/19314111352
或是等待后续发布正式版本
